### ISSUE TITLE
support YAML (or other formats) as example table

### ISSUE THREAD

**Issue by hans-d** [acuminous/yadda#185]
For some tests I have quite some variables. Using separate fields makes the table quite long and hard to use.
Currently adding some YAML inside fields, combined with a custom converter like 
```
  Where:
    | field1 | field2       | field3 |
    |--------|--------------|--------|
    | 1      | some:        | def    |
    |        |   nested: 1  |        |
    |        |   value: abc |        |
    |--------|--------------|--------|
    | 2      | some:        | dfg    |
    |        |   nested: 4  |        |
    |        |   value: cde |        |
```
would be nice if I could it write it like:
```
  Where:
    - field1: 1
      field2:
        some: { nested: 1, value: abc }
     field3: def
   - field1: 2
     field2:
       some: { nested: 4, value: cde }
     field3: dfg
```
Currently cannot yet locate how/where to provide an alternate parsing.
